version: "2.0"

services:

  # https://hub.docker.com/_/postgres/
  postgres:
    container_name: idbase-dev-postgres
    image: postgres:9.6.9-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
      - 5433:5433
    networks:
      - default
    environment:
      - POSTGRES_DB=identitybase
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev

networks:
  default:
    external:
      name: identitybase